name = "ddns"
type = "javascript"
workers_dev = true
compatibility_date = "2022-01-20"

[vars]
ZONE_ID = ""
EMAIL = ""
KEY = ""
COUNTRY = "CN"
"TOKEN_ddns.example.com" = "EXAMPLE_TOKEN"

[build]
command = "cargo install -q worker-build && worker-build --release" # required

[build.upload]
dir    = "build/worker"
format = "modules"
main   = "./shim.mjs"

[[build.upload.rules]]
globs = ["**/*.wasm"]
type  = "CompiledWasm"
